env:
  global:
    - CC_TEST_REPORTER_ID=
language: node_js
node_js:
  - "stable"

after_success: 
  - "npm test"

before_script:
  - npm install nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test

after_script:
  - npm run coverage
  - npm run cc-coverage
  - ./cc-test-reporter format-coverage -t lcov .coverage/lcov.info
  - ./cc-test-reporter upload-coverage $TRAVIS_TEST_RESULT
